# 通过 service方式 暴露es服务

apiVsersion: v1
kind: Service
metadata:
  name: elk-logging
  namespace: elk
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  selector:
    k8s-app: elasticsearch-logging
# spec:
#   containers:
#   - image: docker.io/library/elasticsearch:8.8.0
#     name: es

